### ISSUE TITLE
DogPush is silently ignoring errors

### ISSUE THREAD

**Issue by lextoumbourou** [trueaccord/DogPush#1]
Hi all,

Firstly, thanks a lot for DogPush!

I've noticed that it appears to be silently hiding errors returned from DD's API.

To prove it, I have setup an example config and monitor like this:

```
(dp-test)lex@lex-book2:~/dogpush-test> cat config.yaml

---
datadog:
  api_key: <hidden>
  app_key: <hidden>

rule_files:
  - test.yaml
(dp-test)lex@lex-book2:~/dogpush-test> cat test.yaml
alerts:
- message: "A Test Message"
  name: Test Monitor
  options:
    no_data_timeframe: 480
    renotify_interval: 0
    thresholds: {critical: 20.0, warning: 15.0}
    timeout_h: 0
  query: avg(last_4h):this-isnt-a-query
  tags: ['env:staging']
  type: metric alert
```

Note how the query is totally invalid? 

Then when I run DogPush, it returns a `0` exit code and appears to work successfully, however, the monitor is not updated in Datadog.

```
(dp-test)lex@lex-book2:~/dogpush-test> dogpush push
Pushing 1 new monitors.
(dp-test)lex@lex-book2:~/dogpush-test> echo $?
0
```

If I chuck a print statement where DogPush is creating the alert

```
210         for name in only_local:
211             print datadog.api.Monitor.create(**_prepare_monitor(local_monitors[name]))
```

I note that DD is returning an error about the monitor that we're ignoring:

```
{'errors': ["The value provided for parameter 'query' is invalid"]}
```
